{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "sync-admin-web.fullname" . }}-frontend-tls
  namespace: {{ include "sync-admin-web.resourceNamespace" . }}
  labels:
    {{- include "sync-admin-web.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.ingress.tls.frontendSecretName | quote }}
  issuerRef:
    name: {{ .Values.certManager.issuerName | quote }}
    kind: {{ .Values.certManager.issuerKind | default "ClusterIssuer" | quote }}
  dnsNames:
    - {{ .Values.domain | quote }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "sync-admin-web.fullname" . }}-backend-tls
  namespace: {{ include "sync-admin-web.resourceNamespace" . }}
  labels:
    {{- include "sync-admin-web.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.ingress.tls.backendSecretName | quote }}
  issuerRef:
    name: {{ .Values.certManager.issuerName | quote }}
    kind: {{ .Values.certManager.issuerKind | default "ClusterIssuer" | quote }}
  dnsNames:
    - {{ .Values.serverDomain | quote }}
{{- end }}
