{{- if and .Values.certManager.enabled (.Values.certManager.createClusterIssuer | default false) }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.issuerName }}
  labels:
    {{- include "sync-admin-web.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.certManager.acme.email | quote }}
    server: {{ .Values.certManager.acme.server | quote }}
    privateKeySecretRef:
      name: {{ .Values.certManager.acme.privateKeySecretName }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.certManager.acme.ingressClassName | default "nginx" | quote }}
{{- end }}
