apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sync-admin-web.registrySecretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sync-admin-web.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "sync-admin-web.registrySecretData" . }}
