{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sync-admin-web.fullname" . }}
  namespace: {{ include "sync-admin-web.resourceNamespace" . }}
  labels:
    {{- include "sync-admin-web.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{ include "sync-admin-web.certManagerAnnotationKey" . }}: {{ .Values.certManager.issuerName | quote }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ .Values.domain | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "sync-admin-web.backendFullname" . }}
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /call
            pathType: Prefix
            backend:
              service:
                name: {{ include "sync-admin-web.backendFullname" . }}
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "sync-admin-web.frontendFullname" . }}
                port:
                  number: 80
    - host: {{ .Values.serverDomain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "sync-admin-web.backendFullname" . }}
                port:
                  number: {{ .Values.backend.service.port }}
  tls:
    - secretName: {{ .Values.ingress.tls.frontendSecretName | quote }}
      hosts:
        - {{ .Values.domain | quote }}
    - secretName: {{ .Values.ingress.tls.backendSecretName | quote }}
      hosts:
        - {{ .Values.serverDomain | quote }}
{{- end }}
