{{- if .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sync-admin-web.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sync-admin-web.labels" . | nindent 4 }}
  {{- if .Values.certManager.enabled }}
  annotations:
    {{ include "sync-admin-web.certManagerAnnotationKey" . }}: {{ include "sync-admin-web.certManagerIssuerName" . | quote }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.frontend.ingress.className | default "nginx" }}
  rules:
    {{- range .Values.frontend.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "sync-admin-web.backendFullname" $ }}
                port:
                  number: {{ $.Values.backend.service.port }}
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "sync-admin-web.frontendFullname" $ }}
                port:
                  number: 80
          {{- end }}
    {{- end }}
  {{- if .Values.frontend.ingress.tls }}
  tls:
    {{- range .Values.frontend.ingress.tls }}
    - secretName: {{ .secretName }}
      hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
