apiVersion: v1
kind: Service
metadata:
  name: {{ include "sync-admin-web.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sync-admin-web.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "sync-admin-web.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: 80
