name: Push
"on":
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch: {}
jobs:
  ci:
    name: CI
    run: .action-server/tasks/ci.sh
    timeoutMinutes: 120
