version: 1
name: Nightly
"on":
  schedule:
    - id: nightly
      cron: "15 03 * * *"
      ref: master
  workflow_dispatch: {}
jobs:
  nightly:
    name: Nightly
    required: true
    runsOn: [linux, x64, docker, host]
    executor: host
    run: .cloud-ci/tasks/nightly.sh
    timeoutMinutes: 180
