displayName: Microsoft SQL Server Sync
allowForkPullRequests: false
ignorePushPaths:
  - README.md
favoriteArtifacts:
  windows-portable-agent:
    - sync_windows_agent-windows-portable.zip
    - task-status.json
    - task-results.json
    - task-step-results.json
favoriteTextOutputs:
  windows-portable-agent:
    - workspace/tests/windows-portable-agent-summary.txt
