namespace: sync-admin-web
domain: sync.velvet-leaf.com

certManager:
  enabled: true
  issuerName: letsencrypt-prod
  issuerKind: ClusterIssuer

frontend:
  image:
    repository: sync-admin-web/frontend
    tag: latest
    pullPolicy: Always
  backendBaseUrl: https://sync.velvet-leaf.com/api
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: sync.velvet-leaf.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: sync-velvet-leaf-com-letsencrypt-tls
        hosts:
          - sync.velvet-leaf.com
